"""lnative renderer — generates static HTML/CSS/JS."""

from __future__ import annotations

from uigen.core.components import (
    Button,
    Card,
    Component,
    Form,
    Grid,
    Heading,
    Input,
    Modal,
    Page,
    Select,
    Stack,
    Table,
    Text,
)
from uigen.renderers.base import BaseRenderer


class LNativeRenderer(BaseRenderer):
    """Generates standalone HTML files with Tailwind CSS and vanilla JS."""

    def render_page(self, page: Page, title: str = "") -> str:
        page_title = title or page.title or "Generated by uigen"
        body = self._render_children(page)

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{page_title}</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <style>
        .modal {{ display: none; }}
        .modal.active {{ display: flex; }}
    </style>
</head>
<body class="bg-gray-50 min-h-screen p-8">
    <div class="max-w-6xl mx-auto">
{body}
    </div>
    <script>
        function showModal(id) {{
            document.getElementById(id).classList.add('active');
        }}
        function hideModal(id) {{
            document.getElementById(id).classList.remove('active');
        }}
    </script>
</body>
</html>"""

    def render_component(self, component: Component) -> str:
        renderer = _RENDERERS.get(type(component))
        if renderer is None:
            return self._render_generic(component)
        return renderer(self, component)

    def _render_generic(self, component: Component) -> str:
        classes = (
            " ".join(component.children[0].classes) if component.classes else ""
        )
        children = self._render_children(component)
        return f'<div class="{classes}">{children}</div>'

    def _render_page(self, component: Page) -> str:
        return self._render_children(component)

    def _render_card(self, component: Card) -> str:
        classes = (
            "bg-white rounded-lg shadow-md p-6 " + " ".join(component.classes)
        )
        children = self._render_children(component)
        return f'<div class="{classes}">\n{children}\n</div>'

    def _render_heading(self, component: Heading) -> str:
        tag = f"h{component.level}"
        size_classes = {
            1: "text-3xl font-bold",
            2: "text-2xl font-semibold",
            3: "text-xl font-medium",
            4: "text-lg",
        }
        cls = size_classes.get(component.level, "text-lg")
        return f'<{tag} class="{cls} text-gray-900 mb-4">{component.text}</{tag}>'

    def _render_text(self, component: Text) -> str:
        return f'<p class="text-gray-600">{component.text}</p>'

    def _render_button(self, component: Button) -> str:
        variants = {
            "primary": "bg-blue-600 hover:bg-blue-700 text-white",
            "secondary": "bg-gray-200 hover:bg-gray-300 text-gray-800",
            "danger": "bg-red-600 hover:bg-red-700 text-white",
        }
        cls = variants.get(component.variant, variants["primary"])
        onclick = component.attrs.get("onclick", "")
        attrs = f' onclick="{onclick}"' if onclick else ""
        classes = f'{cls} px-4 py-2 rounded-lg font-medium transition'
        return (
            f'<button class="{classes}"{attrs}>'
            f"{component.text}</button>"
        )

    def _render_input(self, component: Input) -> str:
        label = ""
        if component.label:
            label = (
                '<label class="block text-sm font-medium '
                f'text-gray-700 mb-1">{component.label}</label>'
            )
        attrs = " ".join(f'{k}="{v}"' for k, v in component.attrs.items())
        input_classes = (
            "w-full px-3 py-2 border border-gray-300 rounded-lg "
            "focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
        )
        return f'{label}\n<input {attrs} class="{input_classes}">'

    def _render_select(self, component: Select) -> str:
        label = ""
        if component.label:
            label = (
                '<label class="block text-sm font-medium '
                f'text-gray-700 mb-1">{component.label}</label>'
            )
        options = "\n".join(
            f'<option value="{opt}">{opt}</option>'
            for opt in component.options
        )
        select_classes = (
            "w-full px-3 py-2 border border-gray-300 rounded-lg "
            "focus:ring-2 focus:ring-blue-500"
        )
        return (
            f'{label}\n<select name="{component.name}" '
            f'class="{select_classes}">\n{options}\n</select>'
        )

    def _render_table(self, component: Table) -> str:
        if not component.columns:
            return '<p class="text-gray-500">No data</p>'

        th_classes = (
            "px-4 py-2 text-left text-sm font-medium text-gray-700"
        )
        header = "".join(
            f'<th class="{th_classes}">{col}</th>'
            for col in component.columns
        )

        rows = ""
        for row in component.rows:
            td_classes = "px-4 py-2 text-sm text-gray-600"
            cells = "".join(
                f'<td class="{td_classes}">{row.get(col, "")}</td>'
                for col in component.columns
            )
            rows += (
                f'<tr class="border-t border-gray-200">\n'
                f"{cells}\n</tr>\n"
            )

        return (
            '<table class="w-full">\n'
            f'<thead><tr class="border-b border-gray-200">'
            f"{header}</tr></thead>\n"
            f"<tbody>\n{rows}</tbody>\n</table>"
        )

    def _render_form(self, component: Form) -> str:
        children = self._render_children(component)
        attrs = f' action="{component.action}"' if component.action else ""
        method = component.method
        return (
            f'<form method="{method}"{attrs} class="space-y-4">\n'
            f"{children}\n</form>"
        )

    def _render_modal(self, component: Modal) -> str:
        modal_id = f"modal-{id(component)}"
        children = self._render_children(component)
        title = ""
        if component.title:
            title = (
                '<h2 class="text-xl font-bold mb-4">'
                f"{component.title}</h2>"
            )
        modal_classes = (
            "modal fixed inset-0 bg-black/50 flex items-center "
            "justify-center z-50"
        )
        inner_classes = (
            "bg-white rounded-lg p-6 max-w-md w-full"
        )
        close_classes = "mt-4 text-gray-500 hover:text-gray-700"
        return (
            f'<div id="{modal_id}" class="{modal_classes}">\n'
            f'<div class="{inner_classes}">\n'
            f"{title}\n{children}\n"
            f'<button onclick="hideModal(\'{modal_id}\')" '
            f'class="{close_classes}">Close</button>\n'
            f"</div>\n</div>"
        )

    def _render_grid(self, component: Grid) -> str:
        cols = component.attrs.get("columns", 2)
        children = self._render_children(component)
        return f'<div class="grid grid-cols-{cols} gap-4">\n{children}\n</div>'

    def _render_stack(self, component: Stack) -> str:
        spacing = component.attrs.get("spacing", "md")
        spacing_map = {"sm": "space-y-2", "md": "space-y-4", "lg": "space-y-6"}
        cls = spacing_map.get(spacing, "space-y-4")
        children = self._render_children(component)
        return f'<div class="{cls}">\n{children}\n</div>'


_RENDERERS = {
    Page: LNativeRenderer._render_page,
    Card: LNativeRenderer._render_card,
    Heading: LNativeRenderer._render_heading,
    Text: LNativeRenderer._render_text,
    Button: LNativeRenderer._render_button,
    Input: LNativeRenderer._render_input,
    Select: LNativeRenderer._render_select,
    Table: LNativeRenderer._render_table,
    Form: LNativeRenderer._render_form,
    Modal: LNativeRenderer._render_modal,
    Grid: LNativeRenderer._render_grid,
    Stack: LNativeRenderer._render_stack,
}
