"""CLI — command-line interface for uigen."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path


def main(argv: list[str] | None = None) -> int:
    """Main entry point for the uigen CLI."""
    parser = argparse.ArgumentParser(
        prog="uigen",
        description="Write UI logic once, deploy anywhere.",
    )
    subparsers = parser.add_subparsers(dest="command")

    # uigen init
    init_parser = subparsers.add_parser("init", help="Initialize a new uigen project")
    init_parser.add_argument("name", help="Project name")

    # uigen generate
    gen_parser = subparsers.add_parser("generate", help="Generate frontend code")
    gen_parser.add_argument(
        "--renderer", "-r",
        default="lnative",
        choices=["lnative", "lreact", "lflask", "ldjango"],
        help="Renderer to use (default: lnative)",
    )
    gen_parser.add_argument(
        "--output", "-o",
        default="./dist",
        help="Output directory (default: ./dist)",
    )

    # uigen renderers
    subparsers.add_parser("renderers", help="List available renderers")

    args = parser.parse_args(argv)

    if args.command == "init":
        return _init_project(args.name)
    elif args.command == "generate":
        return _generate(args.renderer, args.output)
    elif args.command == "renderers":
        _list_renderers()
        return 0
    else:
        parser.print_help()
        return 1


def _init_project(name: str) -> int:
    """Initialize a new uigen project."""
    project_dir = Path(name)

    if project_dir.exists():
        print(f"Error: Directory '{name}' already exists.", file=sys.stderr)
        return 1

    project_dir.mkdir(parents=True)

    # Create main.py
    main_file = project_dir / "main.py"
    main_file.write_text(f'''"""Generated by uigen — {name}"""

from uigen import App, Model, ui


class User(Model):
    name: str
    email: str
    role: str = "viewer"


# Build your UI here
page = ui.page(
    ui.card(
        ui.heading("Welcome to {name}"),
        ui.text("Edit main.py to customize this page."),
        ui.button("Get Started"),
    ),
    title="{name}",
)

app = App(title="{name}", pages=[page])

if __name__ == "__main__":
    output = app.render("lnative", output="./dist")
    print(f"Generated UI at {{output}}")
''')

    print(f"Created project: {name}")
    print(f"  cd {name}")
    print("  python main.py")
    return 0


def _generate(renderer: str, output: str) -> int:
    """Generate frontend from main.py."""
    main_file = Path("main.py")
    if not main_file.exists():
        print("Error: No main.py found. Run 'uigen init' first.", file=sys.stderr)
        return 1

    # Execute main.py to get the app object
    import importlib.util
    spec = importlib.util.spec_from_file_location("main", main_file)
    if spec is None or spec.loader is None:
        print("Error: Could not load main.py", file=sys.stderr)
        return 1

    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)

    if not hasattr(module, "app"):
        print(
            "Error: main.py must define an 'app' variable (App instance)",
            file=sys.stderr,
        )
        return 1

    app = module.app
    output_path = app.render(renderer, output=output)
    print(f"Generated {renderer} output at {output_path}")
    return 0


def _list_renderers() -> None:
    """List available renderers."""
    print("Available renderers:")
    print("  lnative  - Static HTML/CSS/JS (ready)")
    print("  lreact   - React components (coming soon)")
    print("  lflask   - Flask/Jinja2 templates (coming soon)")
    print("  ldjango  - Django templates (coming soon)")


if __name__ == "__main__":
    sys.exit(main())
